#### Tarea 4,5 y 6: Haciendo su propio Metropolis-Hastings
* **Forma de entrega**: Como una pestaña de su shiny app showcase
* **Fecha recomendada de terminación**:  octubre (tarea 4) noviembre (tarea 5 y 6)
* **Objetivo**: Esta tarea estará divida en varias tareas. El objetivo es hacer un análisis *regresión lineal simple bayesiana* usando Markov Chain Monte Carlo. El tipo de regresión es 'simple' porque solo vamos a usar una variable explicativa, pero si ustedes desean, pueden hacer todo para regresión múltiple.
El objetivo es *predecir* una variable *Y* usando otra variable aleatoria *X*. El *modelo* está dado por
<div align="center"><pre>
  Y = a + X*beta + eps      con       eps ~ N(0, sigma^2)
</pre></div>
  Los parámetros desconocidos del modelo son theta=(`a`, `beta` y `sigma^2`). Los datos son `(X,Y)`. Si se fijan, en realidad la distribución está asumiendo sore los errores, así que en realidad el modelo está en función de los errores. Por lo tanto, la función de verosimilitud también queda en término de los errores. La función de verosimilitud del modelo es
<pre>
  L(theta) = f(e | theta) =
  = sqrt(2 pi sigma^ 2)^(-N/2)  exp(-e^te/(2 sigma^2))
= sqrt(2 pi sigma^ 2)^(-N/2)  exp((Y-Xb-a)^t(Y-Xb-a)/(2 sigma^2))
</pre>
  donde `e=Y-Xb-a=(e_1,...,e_N)` es el vector de errores. Asegúrense de entender de dónde viene este modelo y porque es como es la verosimilitud. Entenderlo es lo más importante. Si no no deben avanzar.

En un análisis bayesiano suponemos una distribución inicial para estos parámetros. La distribución inicial debe ser un reflejo de su certidumbre o incertidumbre de cierto valor que podría tomar. El usuario debe dar sus suposiciones iniciales.


##### Tarea 4: Diseño de interface y set up inicial

En la primera entrega de la app deben:
  
  1. Escoger una base de datos que quieran usar para problemas de regresión. Pueden usar una base de su trabajo o de otro curso. Si no tienen alguna base que les interese, pueden entrar al repositorio de <a href="archive.ics.uci.edu/ml/">UCL</a> para darse algunas ideas. Esta base la usaran para todas las siguientes tareas.
2. Crear una interface de shiny que utilice las funciones `DT::renderDataTable` y `DT::dataTableOutput` para mostrar su base de datos (vean el tutorial en `http://shiny.rstudio.com/gallery/basic-datatable.html`).
3. En su interface deben elegir dos variables, la variable independiente `Y` y la variable dependiente `X`. Para esto pueden usar la función `selectInput` de Shiny (en caso de que estén haciendo regresión múltiple, pueden usar `checkboxInput`).
4. Hagan un *scatterplot/gráfico de dispersión*. Pueden usar `plotly` o `ggplot2`.
5. Deben elegir una distribución *a priori* para los parámetros de su modelo. Los parámetros de su modelo son el vector `theta=(a, b, sigma^2)`. Ustedes pienses en cómo asignar a prioris.
6. Hagan una gráfica de la función de densidad de su a prioris (una por parámetro)!
  
  ##### Tarea 5: El MCMC
  
  En esta fase de la tarea deben hacer el MCMC. Deben programar una serie de funciones usando el paquete `Rcpp` (go ahead si quieren hacerlo en C/C++ puro... it's up to you.. I would not): la verosimilitud, su a priori, su a posteriori o función objetivo para simular y el MCMC. La función debe regresar la simulación.
                                                                                                                 
                                                                                                                 El shiny debe recibir como parámetros (inputs de shiny, vean funciones como `slideInput` y `numericInput`)
                                                                                                                 
                                                                                                                 1. El número de cadenas que se quieren simular
                                                                                                                 2. La longitud de las cadenas
                                                                                                                 
                                                                                                                 El output debe ser:
                                                                                                                 
                                                                                                                 1. Las simulación de las cadenas. Una matriz numérica de número de filas el número objetivo de simulaciones y de número de columnas el número de cadenas que pidieron simular.
                                                                                                                 2. Deben hacer histogramas de las simulaciones de cada parámetro de su modelo.
                                                                                                                 3. En una gráfica deben comparar la densidad a priori que dieron con la posterior. Para esto, deben estimar la densidad posterior usando la función `density` de R. Aquí hay un ejemplo de como pueden graficar una densidad <a href="http://www.statmethods.net/graphs/density.html">click here</a>. Pero ustedes deben poner la a apriori y la posterior en la misma gráfica. Puede ser bastante laborioso atinarle a los límites de graficación; plotly o ggplot lo hacen por ustedes. Pueden hacer la paquetería de graficación que gusten. Sean creativos; ¡disfrútenlo!
                                                                                                                 
                                                                                                                 *¡El reto más grande que van a tener es elegir el parámetro de brinco!* Es difícil, discútanlo conmigo para ver una solución. Una propuesta muy muy sencilla la pueden encontrar en la página 3 de <a href="http://probability.ca/jeff/ftpdir/adaptex.pdf">clink here</a>. Está basado en la estimación de la matriz de covarianza. Vamos a ver en clase cómo aplicarlo.
                                                                                                                 
                                                                                                                 
                                                                                                                 *Recomendación* (solo enfóquense en esto si ya tienen lo demás) Su cadena sólo debe calcularse cuándo precionen un boton*. Para incluir botones hay que usar las funciones `actionButton` y `observeEvent` o `eventReactive` de shiny. Pueden ver ejemplos en <a href="http://shiny.rstudio.com/articles/action-buttons.html">click here</a>.
                                                                                                                 
                                                                                                                 Si quieren usar programación paralela pueden chechar `RcppParallel` o `doParallel`, en este caso lo dejaremos como optativo.
                                                                                                                 
                                                                                                                 ##### Tarea 6: Diagnósticos
                                                                                                                 En esta tarea deben mejorar su MCMC.
                                                                                                                 
                                                                                                                 
                                                                                                                 ### Fecha de entrega de tareas:
                                                                                                                 Las tareas las voy a revisar el día siguiente del examen final. Pero si quieren feedback de sus tareas pueden entregarlas y mostrarlas en anticipado.